package com.zlebank.zplatform.cmbc.pojo;

// Generated 2016-10-13 9:21:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.util.StringUtils;

import com.zlebank.zplatform.cmbc.common.bean.InsteadPayTradeBean;
import com.zlebank.zplatform.cmbc.common.utils.Constant;
import com.zlebank.zplatform.cmbc.common.utils.DateUtil;

/**
 * TTxnsCmbcInstPayLog generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_CMBC_INST_PAY_LOG")
public class PojoTxnsCmbcInstPayLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String tranId;
	private String tranDate;
	private String tranTime;
	private String merchCd;
	private String PayAcctNo;
	private String payAccName;
	private String payBankType;
	private String paybankName;
	private String accNo;
	private String accName;
	private String bankType;
	private String bankName;
	private Long transAmt;
	private String companyId;
	private String companyDate;
	private String currency;
	private String remarkCd;
	private String remark;
	private String respType;
	private String respCode;
	private String respMsg;
	private String bankTranId;
	private String bankTranDate;
	private String txnseqno;
	private String resResv;
	private String reqResv;
	private String oriTranDate;
	private String oriTranId;
	private String oriBankTranId;
	private String oriBankTranDate;
	private String oriRespType;
	private String oriRespCode;
	private String oriRespMsg;
	public PojoTxnsCmbcInstPayLog() {
	}

	public PojoTxnsCmbcInstPayLog(Long id) {
		this.id = id;
	}
	public PojoTxnsCmbcInstPayLog(String tranId,String txnseqno, String accNo, String accName, String bankType,
			String bankName, Long transAmt, String remark, String reqResv,String merchCd) {
		//this.id = OrderNumber.getInstance().generateTxnsCmbcInsteadRealtimeLogNo();
		//this.companyId = ConsUtil.getInstance().cons.getCmbc_insteadpay_merid();
		this.txnseqno=txnseqno;
		this.merchCd=merchCd;
		this.accName=accName;
		this.accNo = accNo;
		this.bankType=bankType;
		this.bankName=bankName;
		this.transAmt = transAmt;
		this.tranDate = DateUtil.getCurrentDate();
        this.tranTime = DateUtil.getCurrentTime();
        //this.tranId = tranId==null?OrderNumber.getInstance().generateRealTimeInsteadPayOrderNo():tranId;
        this.currency="RMB";
        this.remark=StringUtils.isEmpty(remark)?"证联实时代付":remark;;
        this.reqResv="证联实时代付";
	}
	public PojoTxnsCmbcInstPayLog(String tranId,String txnseqno,Long transAmt, 
			String PayAcctNo, String payAccName, String payBankType, String payBankName,
			String accNo, String accName, String bankType,String bankName, 
			String remark, String reqResv,String merchCd) {
		//this.id = OrderNumber.getInstance().generateTxnsCmbcInsteadRealtimeLogNo();
		//this.companyId = ConsUtil.getInstance().cons.getCmbc_insteadpay_merid();
		this.txnseqno=txnseqno;
		this.merchCd=merchCd;
		this.accName=accName;
		this.accNo = accNo;
		this.bankType=bankType;
		this.bankName=bankName;
		this.transAmt = transAmt;
		this.tranDate = DateUtil.getCurrentDate();
        this.tranTime = DateUtil.getCurrentTime();
        //this.tranId = tranId==null?OrderNumber.getInstance().generateRealTimeInsteadPayOrderNo():tranId;
        this.currency="RMB";
        this.remark=remark;
        this.reqResv="证联实时代付";
	}

	public PojoTxnsCmbcInstPayLog(InsteadPayTradeBean tradeBean) {
		this.companyId = Constant.getInstance().getCmbc_insteadpay_merid();
		this.txnseqno=tradeBean.getTxnseqno();
		this.accName=tradeBean.getAcc_name();
		this.accNo = tradeBean.getAcc_no();
		this.bankType=tradeBean.getBank_type();
		this.bankName=tradeBean.getBank_name();
		this.transAmt = Long.valueOf(tradeBean.getTrans_amt());
		this.tranDate = DateUtil.getCurrentDate();
        this.tranTime = DateUtil.getCurrentTime();
        this.currency="RMB";
        this.remark=StringUtils.isEmpty(remark)?"证联实时代付":remark;;
        this.reqResv="证联实时代付";
	}
	public PojoTxnsCmbcInstPayLog(Long id, String tranId, String tranTime,
			String merchCd, String accNo, String accName, String bankType,
			String bankName, Long transAmt, String companyId, String tranDate,
			String currency, String remark, String respType, String respCode,
			String respMsg, String bankTranId, String bankTranDate,
			String txnseqno, String resResv, String reqResv) {
		this.id = id;
		this.tranId = tranId;
		this.tranTime = tranTime;
		this.merchCd = merchCd;
		this.accNo = accNo;
		this.accName = accName;
		this.bankType = bankType;
		this.bankName = bankName;
		this.transAmt = transAmt;
		this.companyId = companyId;
		this.tranDate = tranDate;
		this.currency = currency;
		this.remark = remark;
		this.respType = respType;
		this.respCode = respCode;
		this.respMsg = respMsg;
		this.bankTranId = bankTranId;
		this.bankTranDate = bankTranDate;
		this.txnseqno = txnseqno;
		this.resResv = resResv;
		this.reqResv = reqResv;
	}

	@Id
	 @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_txns_cmbc_inst_pay_log") 
	 @SequenceGenerator(name="seq_txns_cmbc_inst_pay_log",sequenceName="SEQ_TXNS_CMBC_INST_PAY_LOG",allocationSize=1)
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TRAN_ID", length = 32)
	public String getTranId() {
		return this.tranId;
	}

	public void setTranId(String tranId) {
		this.tranId = tranId;
	}

	@Column(name = "TRAN_TIME", length = 6)
	public String getTranTime() {
		return this.tranTime;
	}

	public void setTranTime(String tranTime) {
		this.tranTime = tranTime;
	}

	@Column(name = "MERCH_CD", length = 15)
	public String getMerchCd() {
		return this.merchCd;
	}

	public void setMerchCd(String merchCd) {
		this.merchCd = merchCd;
	}

	@Column(name = "ACC_NO", length = 40)
	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	@Column(name = "ACC_NAME", length = 128)
	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	@Column(name = "BANK_TYPE", length = 12)
	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	@Column(name = "BANK_NAME", length = 128)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "TRANS_AMT", precision = 12, scale = 0)
	public Long getTransAmt() {
		return this.transAmt;
	}

	public void setTransAmt(Long transAmt) {
		this.transAmt = transAmt;
	}

	@Column(name = "COMPANY_ID", length = 7)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "TRAN_DATE", length = 8)
	public String getTranDate() {
		return this.tranDate;
	}

	public void setTranDate(String tranDate) {
		this.tranDate = tranDate;
	}

	@Column(name = "CURRENCY", length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "REMARK", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RESP_TYPE", length = 1)
	public String getRespType() {
		return this.respType;
	}

	public void setRespType(String respType) {
		this.respType = respType;
	}

	@Column(name = "RESP_CODE", length = 8)
	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	@Column(name = "RESP_MSG")
	public String getRespMsg() {
		return this.respMsg;
	}

	public void setRespMsg(String respMsg) {
		this.respMsg = respMsg;
	}

	@Column(name = "BANK_TRAN_ID", length = 32)
	public String getBankTranId() {
		return this.bankTranId;
	}

	public void setBankTranId(String bankTranId) {
		this.bankTranId = bankTranId;
	}

	@Column(name = "BANK_TRAN_DATE", length = 8)
	public String getBankTranDate() {
		return this.bankTranDate;
	}

	public void setBankTranDate(String bankTranDate) {
		this.bankTranDate = bankTranDate;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "RES_RESV", length = 512)
	public String getResResv() {
		return this.resResv;
	}

	public void setResResv(String resResv) {
		this.resResv = resResv;
	}

	@Column(name = "REQ_RESV", length = 512)
	public String getReqResv() {
		return this.reqResv;
	}

	public void setReqResv(String reqResv) {
		this.reqResv = reqResv;
	}
	@Column(name = "PAY_ACCT_NO", length = 40)
	public String getPayAcctNo() {
		return PayAcctNo;
	}

	public void setPayAcctNo(String PayAcctNo) {
		this.PayAcctNo = PayAcctNo;
	}
	@Column(name = "PAY_ACC_NAME", length = 128)
	public String getPayAccName() {
		return payAccName;
	}

	public void setPayAccName(String payAccName) {
		this.payAccName = payAccName;
	}
	@Column(name = "PAY_BANK_TYPE", length = 12)
	public String getPayBankType() {
		return payBankType;
	}

	public void setPayBankType(String payBankType) {
		this.payBankType = payBankType;
	}
	@Column(name = "PAY_BANK_NAME", length = 128)
	public String getPaybankName() {
		return paybankName;
	}

	public void setPaybankName(String paybankName) {
		this.paybankName = paybankName;
	}
	@Column(name = "COMPANY_DATE", length = 8)
	public String getCompanyDate() {
		return companyDate;
	}

	public void setCompanyDate(String companyDate) {
		this.companyDate = companyDate;
	}
	@Column(name = "REMARK_CD", length = 5)
	public String getRemarkCd() {
		return remarkCd;
	}

	public void setRemarkCd(String remarkCd) {
		this.remarkCd = remarkCd;
	}
	@Column(name = "ORI_TRAN_DATE", length = 8)
	public String getOriTranDate() {
		return this.oriTranDate;
	}

	public void setOriTranDate(String oriTranDate) {
		this.oriTranDate = oriTranDate;
	}

	@Column(name = "ORI_TRAN_ID", length = 32)
	public String getOriTranId() {
		return this.oriTranId;
	}

	public void setOriTranId(String oriTranId) {
		this.oriTranId = oriTranId;
	}

	@Column(name = "ORI_BANK_TRAN_ID", length = 32)
	public String getOriBankTranId() {
		return this.oriBankTranId;
	}

	public void setOriBankTranId(String oriBankTranId) {
		this.oriBankTranId = oriBankTranId;
	}

	@Column(name = "ORI_BANK_TRAN_DATE", length = 8)
	public String getOriBankTranDate() {
		return this.oriBankTranDate;
	}

	public void setOriBankTranDate(String oriBankTranDate) {
		this.oriBankTranDate = oriBankTranDate;
	}

	@Column(name = "ORI_RESP_TYPE", length = 1)
	public String getOriRespType() {
		return this.oriRespType;
	}

	public void setOriRespType(String oriRespType) {
		this.oriRespType = oriRespType;
	}

	@Column(name = "ORI_RESP_CODE", length = 8)
	public String getOriRespCode() {
		return this.oriRespCode;
	}

	public void setOriRespCode(String oriRespCode) {
		this.oriRespCode = oriRespCode;
	}

	@Column(name = "ORI_RESP_MSG", length = 512)
	public String getOriRespMsg() {
		return this.oriRespMsg;
	}

	public void setOriRespMsg(String oriRespMsg) {
		this.oriRespMsg = oriRespMsg;
	}


}
